// Mocks generated by Mockito 5.4.4 from annotations
// in sunshine/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:convert' as _i27;
import 'dart:typed_data' as _i29;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i22;
import 'package:http/http.dart' as _i10;
import 'package:intl/intl.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i28;
import 'package:sunshine/core/error/failure.dart' as _i12;
import 'package:sunshine/data/datasource/location_remote_data_source.dart'
    as _i25;
import 'package:sunshine/data/datasource/weather_remote_data_source.dart'
    as _i15;
import 'package:sunshine/data/model/five_day_forecast_model.dart' as _i4;
import 'package:sunshine/data/model/location_model.dart' as _i26;
import 'package:sunshine/data/model/weather_model.dart' as _i3;
import 'package:sunshine/domain/entities/five_day_forecast_entity.dart' as _i14;
import 'package:sunshine/domain/entities/location.dart' as _i19;
import 'package:sunshine/domain/entities/weather.dart' as _i13;
import 'package:sunshine/domain/repositories/location_repository.dart' as _i6;
import 'package:sunshine/domain/repositories/weather_repository.dart' as _i5;
import 'package:sunshine/domain/usecases/get_current_weather.dart' as _i16;
import 'package:sunshine/domain/usecases/get_five_day_forecast.dart' as _i17;
import 'package:sunshine/domain/usecases/search_location_by_city_name.dart'
    as _i18;
import 'package:sunshine/presentation/home/bloc/forecast_bloc.dart' as _i23;
import 'package:sunshine/presentation/home/bloc/forecast_event.dart' as _i24;
import 'package:sunshine/presentation/home/bloc/forecast_state.dart' as _i9;
import 'package:sunshine/presentation/home/bloc/home_bloc.dart' as _i20;
import 'package:sunshine/presentation/home/bloc/home_event.dart' as _i21;
import 'package:sunshine/presentation/home/bloc/home_state.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherModel_1 extends _i1.SmartFake implements _i3.WeatherModel {
  _FakeWeatherModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFiveDayForecastModel_2 extends _i1.SmartFake
    implements _i4.FiveDayForecastModel {
  _FakeFiveDayForecastModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherRepository_3 extends _i1.SmartFake
    implements _i5.WeatherRepository {
  _FakeWeatherRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationRepository_4 extends _i1.SmartFake
    implements _i6.LocationRepository {
  _FakeLocationRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateFormat_5 extends _i1.SmartFake implements _i7.DateFormat {
  _FakeDateFormat_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeState_6 extends _i1.SmartFake implements _i8.HomeState {
  _FakeHomeState_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForecastState_7 extends _i1.SmartFake implements _i9.ForecastState {
  _FakeForecastState_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_8 extends _i1.SmartFake implements _i10.Response {
  _FakeResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_9 extends _i1.SmartFake
    implements _i10.StreamedResponse {
  _FakeStreamedResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i5.WeatherRepository {
  MockWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.Either<_i12.Failure, _i13.WeatherEntity>> getCurrentWeather(
          String? cityName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [cityName],
        ),
        returnValue:
            _i11.Future<_i2.Either<_i12.Failure, _i13.WeatherEntity>>.value(
                _FakeEither_0<_i12.Failure, _i13.WeatherEntity>(
          this,
          Invocation.method(
            #getCurrentWeather,
            [cityName],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, _i13.WeatherEntity>>);

  @override
  _i11.Future<
      _i2.Either<_i12.Failure, _i14.FiveDayForecastEntity>> getFiveDayForecast({
    required double? lat,
    required double? lon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFiveDayForecast,
          [],
          {
            #lat: lat,
            #lon: lon,
          },
        ),
        returnValue: _i11
            .Future<_i2.Either<_i12.Failure, _i14.FiveDayForecastEntity>>.value(
            _FakeEither_0<_i12.Failure, _i14.FiveDayForecastEntity>(
          this,
          Invocation.method(
            #getFiveDayForecast,
            [],
            {
              #lat: lat,
              #lon: lon,
            },
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, _i14.FiveDayForecastEntity>>);
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i15.WeatherRemoteDataSource {
  MockWeatherRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i3.WeatherModel> getCurrentWeather(String? cityName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [cityName],
        ),
        returnValue: _i11.Future<_i3.WeatherModel>.value(_FakeWeatherModel_1(
          this,
          Invocation.method(
            #getCurrentWeather,
            [cityName],
          ),
        )),
      ) as _i11.Future<_i3.WeatherModel>);

  @override
  _i11.Future<_i4.FiveDayForecastModel> getFiveDayForecast({
    required double? lat,
    required double? lon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFiveDayForecast,
          [],
          {
            #lat: lat,
            #lon: lon,
          },
        ),
        returnValue: _i11.Future<_i4.FiveDayForecastModel>.value(
            _FakeFiveDayForecastModel_2(
          this,
          Invocation.method(
            #getFiveDayForecast,
            [],
            {
              #lat: lat,
              #lon: lon,
            },
          ),
        )),
      ) as _i11.Future<_i4.FiveDayForecastModel>);
}

/// A class which mocks [GetCurrentWeatherUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentWeatherUseCase extends _i1.Mock
    implements _i16.GetCurrentWeatherUseCase {
  MockGetCurrentWeatherUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.WeatherRepository get weatherRepository => (super.noSuchMethod(
        Invocation.getter(#weatherRepository),
        returnValue: _FakeWeatherRepository_3(
          this,
          Invocation.getter(#weatherRepository),
        ),
      ) as _i5.WeatherRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, _i13.WeatherEntity>> execute(
          String? cityName) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [cityName],
        ),
        returnValue:
            _i11.Future<_i2.Either<_i12.Failure, _i13.WeatherEntity>>.value(
                _FakeEither_0<_i12.Failure, _i13.WeatherEntity>(
          this,
          Invocation.method(
            #execute,
            [cityName],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, _i13.WeatherEntity>>);
}

/// A class which mocks [GetFiveDayForecastUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFiveDayForecastUseCase extends _i1.Mock
    implements _i17.GetFiveDayForecastUseCase {
  MockGetFiveDayForecastUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.WeatherRepository get weatherRepository => (super.noSuchMethod(
        Invocation.getter(#weatherRepository),
        returnValue: _FakeWeatherRepository_3(
          this,
          Invocation.getter(#weatherRepository),
        ),
      ) as _i5.WeatherRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, _i14.FiveDayForecastEntity>> execute(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            lat,
            lon,
          ],
        ),
        returnValue: _i11
            .Future<_i2.Either<_i12.Failure, _i14.FiveDayForecastEntity>>.value(
            _FakeEither_0<_i12.Failure, _i14.FiveDayForecastEntity>(
          this,
          Invocation.method(
            #execute,
            [
              lat,
              lon,
            ],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, _i14.FiveDayForecastEntity>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, _i14.FiveDayForecastEntity>> call(
          _i17.GetFiveDayForecastParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i11
            .Future<_i2.Either<_i12.Failure, _i14.FiveDayForecastEntity>>.value(
            _FakeEither_0<_i12.Failure, _i14.FiveDayForecastEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, _i14.FiveDayForecastEntity>>);
}

/// A class which mocks [SearchLocationsByCityNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchLocationsByCityNameUseCase extends _i1.Mock
    implements _i18.SearchLocationsByCityNameUseCase {
  MockSearchLocationsByCityNameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.LocationRepository get locationRepository => (super.noSuchMethod(
        Invocation.getter(#locationRepository),
        returnValue: _FakeLocationRepository_4(
          this,
          Invocation.getter(#locationRepository),
        ),
      ) as _i6.LocationRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i19.LocationEntity>>> call(
          _i18.SearchLocationsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i11
            .Future<_i2.Either<_i12.Failure, List<_i19.LocationEntity>>>.value(
            _FakeEither_0<_i12.Failure, List<_i19.LocationEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i19.LocationEntity>>>);
}

/// A class which mocks [HomeBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeBloc extends _i1.Mock implements _i20.HomeBloc {
  MockHomeBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.DateFormat get f => (super.noSuchMethod(
        Invocation.getter(#f),
        returnValue: _FakeDateFormat_5(
          this,
          Invocation.getter(#f),
        ),
      ) as _i7.DateFormat);

  @override
  _i8.HomeState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeHomeState_6(
          this,
          Invocation.getter(#state),
        ),
      ) as _i8.HomeState);

  @override
  _i11.Stream<_i8.HomeState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i8.HomeState>.empty(),
      ) as _i11.Stream<_i8.HomeState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i21.HomeEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i21.HomeEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i8.HomeState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i21.HomeEvent>(
    _i22.EventHandler<E, _i8.HomeState>? handler, {
    _i22.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i22.Transition<_i21.HomeEvent, _i8.HomeState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void onChange(_i22.Change<_i8.HomeState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ForecastBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockForecastBloc extends _i1.Mock implements _i23.ForecastBloc {
  MockForecastBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.DateFormat get f => (super.noSuchMethod(
        Invocation.getter(#f),
        returnValue: _FakeDateFormat_5(
          this,
          Invocation.getter(#f),
        ),
      ) as _i7.DateFormat);

  @override
  _i7.DateFormat get weekdayFormatter => (super.noSuchMethod(
        Invocation.getter(#weekdayFormatter),
        returnValue: _FakeDateFormat_5(
          this,
          Invocation.getter(#weekdayFormatter),
        ),
      ) as _i7.DateFormat);

  @override
  _i9.ForecastState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeForecastState_7(
          this,
          Invocation.getter(#state),
        ),
      ) as _i9.ForecastState);

  @override
  _i11.Stream<_i9.ForecastState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i9.ForecastState>.empty(),
      ) as _i11.Stream<_i9.ForecastState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i24.ForecastEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i24.ForecastEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i9.ForecastState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i24.ForecastEvent>(
    _i22.EventHandler<E, _i9.ForecastState>? handler, {
    _i22.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i22.Transition<_i24.ForecastEvent, _i9.ForecastState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void onChange(_i22.Change<_i9.ForecastState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i6.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<
      _i2.Either<_i12.Failure, List<_i19.LocationEntity>>> searchCityListByName(
          String? cityName) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCityListByName,
          [cityName],
        ),
        returnValue: _i11
            .Future<_i2.Either<_i12.Failure, List<_i19.LocationEntity>>>.value(
            _FakeEither_0<_i12.Failure, List<_i19.LocationEntity>>(
          this,
          Invocation.method(
            #searchCityListByName,
            [cityName],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i19.LocationEntity>>>);
}

/// A class which mocks [LocationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRemoteDataSource extends _i1.Mock
    implements _i25.LocationRemoteDataSource {
  MockLocationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i26.LocationModel>> searchCityListByName(
          String? cityName) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCityListByName,
          [cityName],
        ),
        returnValue:
            _i11.Future<List<_i26.LocationModel>>.value(<_i26.LocationModel>[]),
      ) as _i11.Future<List<_i26.LocationModel>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i10.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i10.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<_i10.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<_i10.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<_i10.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<_i10.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<_i10.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i11.Future<String>.value(_i28.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<_i29.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i11.Future<_i29.Uint8List>.value(_i29.Uint8List(0)),
      ) as _i11.Future<_i29.Uint8List>);

  @override
  _i11.Future<_i10.StreamedResponse> send(_i10.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i11.Future<_i10.StreamedResponse>.value(_FakeStreamedResponse_9(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i11.Future<_i10.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
